config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'

  namespace :admin do
    resources :families, only: [:show, :new, :edit, :create, :update, :destroy] do
      resources :supply_items, only: [:edit, :update]
    end
  end

  resources :families, only: [:index, :show] do
    resources :supply_items, only: [:edit, :update, :show]
  end


  resources :users, only: [:new, :create, :show]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  
end

app/models/family.rb
class Family < ActiveRecord::Base
  has_many :supply_items, dependent: :destroy
  has_many :supplies, through: :supply_items


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :arrival_date, presence: true
  # validates :deadline, presence: true
  validates :nationality, presence: true
  validates :num_married_adults, presence: true
  validates :num_non_married_adults, presence: true
  validates :num_children_over_two, presence: true
  validates :num_children_under_two, presence: true

  def self.to_arrive
    Family.where('arrival_date > ?', DateTime.now)
  end


# <%= image_tag "rails.png" %>


  def num_people
    num_married_adults + num_non_married_adults + num_children_over_two + num_children_under_two
  end

  def num_twin_beds
    num_people - num_married_adults - num_children_under_two
  end

  def num_full_beds
    num_married_adults/2
  end

  def num_dressers
    num_people > 4 ? 4 : num_people
  end

  def num_couches
    num_people > 6 ? 2 : 1
  end


  def supply_item_hash
    {"Twin Bedframe" => num_twin_beds, "Twin Mattress" => num_twin_beds, "Full Bedframe" => num_full_beds, "Full Mattress" => num_full_beds, "Dresser" => num_dressers, "Couch" => num_couches, "Kitchen Table" => 1, "Kitchen Chair" => num_people, "Crib" => num_children_under_two, "Silverware Set" => num_people, "Large Pot" => 1, "Small Pot" => 1}
  end

  def create_supply_items
    supply_item_hash.each do |item_name, quantity|
      supply_items.create(supply: Supply.find_by(name: item_name), quantity: quantity)
    end

  end




end

app/models/supply.rb
class Supply < ActiveRecord::Base
  has_many :supply_items
end

app/models/supply_item.rb
class SupplyItem < ActiveRecord::Base
  belongs_to :family
  belongs_to :supply
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :supply_items
  validates :username, presence: true, uniqueness: true


  enum role: ["default", "admin"]

  def items_donated
    SupplyItem.where(user: self, status: "Received")
  end


  def items_pledged
    SupplyItem.where(user: self, status: "Pledged")
  end


end

app/controllers/admin/base_controller.rb
class Admin::BaseController <ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end

end

app/controllers/admin/families_controller.rb
class Admin::FamiliesController <Admin::BaseController

  def new
    @family = Family.new
  end

  def show
    @family = Family.find(params[:id])
    @supply_items = @family.supply_items
  end

  def create
    @family = Family.new(family_params)
    if @family.save
      flash[:notice] = "Family created successfully.  Please review supply list"
      @family.create_supply_items
      redirect_to admin_family_path(@family)
    else
      flash.now[:error] = @family.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @family = Family.find(params[:id])
  end

  def update
    @family = Family.find(params[:id])
    if @family.update(family_params)
      flash[:notice] = "Family updated successfully. Please review supply list."
      redirect_to admin_family_path(@family)
    else
      flash.now[:error] = @family.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @family = Family.find(params[:id])
    @family.destroy
    flash[:notice] = "Family deleted"
    redirect_to families_path
  end

  private

  def family_params
    params.require(:family).permit(:first_name, :last_name, :address, :arrival_date, :nationality, :description, :num_married_adults, :num_non_married_adults, :num_children_over_two, :num_children_under_two)
  end

end

app/controllers/admin/supply_items_controller.rb
class Admin::SupplyItemsController <Admin::BaseController

  def edit
    @family = Family.find(params[:family_id])
    @supply_items = @family.supply_items.all
  end

  def update
    @family = Family.find(params[:family_id])
    @supply_item = SupplyItem.find(params[:id])
    @supply_item.update(supply_item_params)
    flash[:notice] = "Supply item updated successfully"
    redirect_to admin_family_path(@family)

  end

  def supply_item_params
    params.require(:supply_item).permit(:quantity, :status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
# you can look into scoping this down the current user by creating a before action for
# the current user.
#so instead of having the if/else statement in the families to take care of the current_user
# you can deal with it as the user visits your page.
# --------------------------

  #before_action :require_authenticated_user

  #def require_authenticated_user
    #redirect_to login_path flash[:login] ="Must Login" unless current_user
  #end

# --------------------------
  def index
    @families = Family.to_arrive
  end

  def show
    @family = Family.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController

  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:alert] = "Login successful"
      redirect_to families_path
    else
      flash.now[:error] = "Invalid login.  Try again"
      render :new
    end

  end


  def destroy
    flash[:alert] = "Logout successful"
    session.clear
    redirect_to login_path
  end


end

app/controllers/supply_items_controller.rb
class SupplyItemsController <ApplicationController

  def update
    @family = Family.find(params[:family_id])
    @supply_item = SupplyItem.find(params[:id])
    @supply_item.status = "Pledged"
    @supply_item.user = current_user
    @supply_item.save
    flash[:alert] = "Donation saved"
    redirect_to family_path(@family)
  end

end

app/controllers/users_controller.rb
class UsersController <ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:alert] = "Account Created.  Please login."
      redirect_to login_path
    else
      flash.now[:error] = @family.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @user = current_user
  end



  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController <ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/families/_form.html.erb
<%= # love your partial! %>
<%= form_for [:admin, @family], :html => {:class => "form-horizontal"} do |f| %>

<div class="form-group">
  <%= f.label :first_name  %>
  <%= f.text_field :first_name, class: "form-control"   %></br>
</div>
<div class="form-group">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: "form-control" %></br>

</div>

<div class="form-group">
  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %></br>

</div>
<div class="form-group">
  <%= f.label :arrival_date %>
  <%= f.date_field :arrival_date, class: "form-control" %></br>

</div>
<div class="form-group">
  <%= f.label :deadline %>
  <%= f.date_field :deadline, class: "form-control"%></br>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %></br>
</div>

<div class="form-group">
  <%= f.label :nationality %>
  <%= f.select :nationality, ["Afghan", "Burmese", "Iraq", "Other", "Somali", "Sudanese", "Syrian"], class: "form-control" %></br>
</div>

<div class="form-group">
  <%= f.label "Number of Married Adults in Household:" %>
  <%= f.select :num_married_adults, (0..6), class: "form-control" %></br>

</div>
<div class="form-group">
  <%= f.label "Number of Unmarried Adults in Household:" %>
  <%= f.select :num_non_married_adults, (0..6), class: "form-control" %></br>

</div>
<div class="form-group">
  <%= f.label "Number of Children over 2 in Household:"%>
  <%= f.select :num_children_over_two, (0..10), class: "form-control" %></br>

</div>

<div class="form-group">
  <%= f.label "Number of Children Under 2 in Household:" %>
  <%= f.select :num_children_under_two, (0..4), class: "form-control" %></br>

</div>

  <%= f.submit %>


<% end %>

app/views/admin/families/edit.html.erb
<h1>Edit information for refugee family:</h1>

<%= render partial: "form" %>

app/views/admin/families/new.html.erb
<h1>Enter information about refugee family scheduled to arrive:</h1>

<%= render partial: "form" %>

app/views/admin/families/show.html.erb
<div class="container">
<%= button_to "Back to Family List", families_path, :method => "get", class: "btn btn-primary" %>
</div>

<%= render partial: "/shared/family_profile" %>

<h4>Supply List</h4>
<table class="table">
  <tr>
    <th>Supply</th>
    <th>Quantity</th>
    <th>Status</th>
    <th></th>
  </tr>


    <% @family.supply_items.each do |supply_item| %>
    <tr>

      <%= form_for [:admin, @family, supply_item], :html => {:class => "form #{supply_item.supply.name}"} do |f| %>
      <td><%= supply_item.supply.name %></td>
      <td>
      <div class="form-group">
        <%= f.text_field :quantity, class: "form-control"   %></br>
      </div>
      </td>
      <td>
      <div class="form-group">
        <%= f.select(:status, ["Needed", "Pledged", "Received"], { :prompt => 'Select', :selected => supply_item.status }, { class: 'form-control' }) %></br>
      </div>

      </td>

      <td>

      <%= f.submit "Update" %>

      </td>
      <% end %>

    <% end %>
</table>

app/views/families/_form.html.erb
<%= form_for @family do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %></br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %></br>
  <%= f.label :address %>
  <%= f.text_field :address %></br>
  <%= f.label :arrival_date %>
  <%= f.date_field :arrival_date %></br>
  <%= f.label :nationality %>
  <%= f.text_field :nationality %></br>
  <%= f.label :description %>
  <%= f.text_area :description %></br>

  <%= f.label "Number of Married Adults in Household:" %>
  <%= f.select :num_married_adults, (0..6) %></br>
  <%= f.label "Number of Unmarried Adults in Household:" %>
  <%= f.select :num_non_married_adults, (0..6) %></br>
  <%= f.label "Number of Children over 2 in Household:" %>
  <%= f.select :num_children_over_two, (0..10) %></br>
  <%= f.label "Number of Children Under 2 in Household:" %>
  <%= f.select :num_children_under_two, (0..4) %></br>
  <%= f.submit %>


<% end %>

app/views/families/index.html.erb
<% if current_admin? %>
  <%= button_to "Add a new family", new_admin_family_path, :method => "get", class: "btn btn-primary" %>
  <h1>Refugee Families Scheduled to Arrive</h1>

<% else %>
  <h1>Help Welcome a Refugee Family</h1>
<% end %>

<div class="families">

<% @families.each do |family| %>
  <% if current_admin? %>
    <h4><%=family.last_name%>, <%=family.first_name%></h4>
    <%= link_to "(Edit Family)", edit_admin_family_path(family) %>
    <%= link_to "(Edit Supplies)", admin_family_path(family) %>
    <%= link_to "(Delete Family)", admin_family_path(family), method: :delete %>

  <% else %>
    <h4><%= link_to "#{family.nationality} family of #{family.num_people}", family_path(family) %></h4>
  <% end %>
  <p>Arrival Date: <%= family.arrival_date.to_date %> </p>

<% end %>

</div>

<div class="tweets">
  <h4>Latest Tweets from UN Refugee Agency</h4>
  <ul>
  <% TwitterApi.get_tweets.each do |tweet| %>
    <li><%= tweet.text%></li>
  <% end %>
  </ul>
</div>

app/views/families/show.html.erb
<% if current_admin? %>

  <div class="btn-group btn-group-justified">

  <%= button_to "Edit Family", edit_admin_family_path(@family), :method => "get", class: "btn btn-primary" %>

  <%= button_to "Delete Family", admin_family_path(@family), :method => "delete", class: "btn btn-primary" %>

  <%= button_to "Edit Supplies", admin_family_path(@family), :method => "get", class: "btn btn-primary" %>

  </div>
<% end %>


<div class="">

  <%= render partial: "/shared/family_profile" %>



</div>


<div class="col-sm-12 container"></div>


<h4>Supply List</h4>
<table class="table">
  <tr>
    <th>Supply</th>
    <th>Quantity</th>
    <th>Status</th>
    <th>Donation Information</th>
  </tr>

<% @family.supply_items.each do |supply_item| %>
<tr>
    <% if supply_item.quantity > 0 %>
      <%= form_for [@family, supply_item], :html => {:class =>  supply_item.supply.name} do |f| %>
      <td><%= supply_item.supply.name %></td>
      <td><%= supply_item.quantity %></td>
      <td><%= supply_item.status %></td>
      <td>
    
        <% if  supply_item.status == "Pledged" && supply_item.user%>
          <p>Pledged by: <%=supply_item.user.username %></p>

        <% elsif  supply_item.status == "Received" && supply_item.user%>
          <p>Received From: <%=supply_item.user.username %></p>

        <% elsif supply_item.status == "Needed" && current_user%>
          <%= f.submit "Donate" %>

        <% elsif !current_user%>
          <%= link_to "Login to Donate", login_path %>
        <% end %>
      </td>
    <% end %>

  <% end %>

</tr>

<% end %>


</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RefugeeDonations</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
</head>
<body>

  <nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">RefugeesWelcome</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-left">
        <li><a href="/families">Families</a></li>
        <% if current_user %>
        <li><a href="/users/<%=current_user.id %>">Profile</a></li>
        <% end %>
      </ul>


      <% if current_user %>
        <p class="navbar-brand pull-right">Welcome, <%= current_user.username %> </p>
        <%= link_to "Logout", logout_path, method: :delete, class: "navbar-brand pull-right"%>

      <% else %>
        <%= link_to "Login", login_path,class: "navbar-brand pull-right"%>
        <%= link_to "Create Account", new_user_path, class: "navbar-brand pull-right"%>
      <% end %>

    </div>
  </div>
</nav>

<% flash.each do |type, msg| %>
  <% if type == "error" %>
    <%= content_tag :div, msg, class: "flash-#{type} alert alert-danger container" %>
  <% else %>
    <%= content_tag :div, msg, class: "flash-#{type} alert alert-success container" %>
  <% end %>
<% end %>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/shared/_family_profile.html.erb
<%= #beautiful partials for the win  %>

<div class="col-sm-5">
  <%= image_tag "#{@family.nationality}.jpeg" %>
</div>

<div class="col-sm-7 ">
<% if current_admin? %>
  <h2>Name: <%= @family.last_name %>, <%= @family.first_name %></h2>

<% else %>
  <h2> <%=@family.nationality%> family of <%=@family.num_people%></h2>
<% end %>

<p>Scheduled to Arrive: <%= @family.arrival_date.to_date %></h4>

<p>Description: <%= @family.description %></p>
<p>Nationality: <%= @family.nationality %> </p>

<p>Family Composition:</p>

<table class="table">
  <tr>
    <td>Married Adults: </td>
    <td><%= @family.num_married_adults %></td>
    <td>Unmarried Adults:</td>
    <td><%= @family.num_non_married_adults %></td>
  </tr>

  <tr>
    <td>Children over 2: </td>
    <td><%= @family.num_children_over_two %></td>
    <td>Children under 2:</td>
    <td><%= @family.num_children_under_two %></td>
  </tr>

</table>

</div>

app/views/users/new.html.erb
<h1>Create a New Account:</h1>
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.submit "Create Account"%>
<% end %>

app/views/users/show.html.erb
<h2>My Profile</h2>

<h4>Name: <%=current_user.username%> </h4>
<h4>Joined On: <%=current_user.created_at.to_date%> </h4>

<div class="donated">


<h2>Items I've Donated:</h2>

<% if @user.items_donated %>
  <% @user.items_donated.each do |item| %>
    <h4> <%= item.family.nationality%> family arrived on: <%= item.family.arrival_date.to_date %></h4>
    <p>Supply: <%= item.supply.name %></p>
    <p>Quantity: <%= item.quantity %></p>
  <% end %>
<% end %>

</div>

<div class="pledged">



<h2>Items I've Pledged:</h2>

<% if @user.items_pledged %>
  <% @user.items_pledged.each do |item| %>
    <h4> <%= item.family.nationality%> family arrving on: <%= item.family.arrival_date.to_date %></h4>
    <p>Supply: <%= item.supply.name %></p>
    <p>Quantity: <%= item.quantity %></p>
  <% end %>

<% end %>

</div>

<%= button_to "Welcome a new Family", families_path, :method => "get", class: "btn btn-primary" %>

app/views/welcome/index.html.erb
  <div class="cover-story col-sm-3">

  <p>Imagine <span class="pop">fleeing your home</span> with just a backpack</p>
  <a href="https://medium.com/uprooted/what-s-in-my-bag-758d435f6e62#.yx166rox8">Read the story here.</a>

  <p>Crossing an <span class="pop">ocean in a raft, </span> only to find the borders closed</p>
  <a href="https://medium.com/uprooted/stranded-lives-3aedc80c1337#.jlsgtlysv">Read the story here.</a>

  <p>Getting the chance to <span class="pop">start over in America</span></p>

  <p> Arriving with sparse possessions, <span class="pop">no money</span>, little English, and few prospects.</p>

  <h3>But welcomed by <span class="pop">safety, freedom and the generosity</span> of the American people.</h3>

<% if current_user %>
  <%= button_to "Make #RefugeesWelcome", families_path, :method => "get", class: "btn btn-primary" %>

<% else %>
  <%= button_to "Make #RefugeesWelcome", new_user_path, :method => "get", class: "btn btn-primary" %>
<%end  %>

  </div>

  <div class="cover-photo col-sm-8">
  <%= image_tag "SyriaCover.jpeg"%>
  </div>